# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(836, 738)
        self.solveProblem_Btn = QtWidgets.QPushButton(Dialog)
        self.solveProblem_Btn.setGeometry(QtCore.QRect(20, 680, 411, 41))
        self.solveProblem_Btn.setObjectName("solveProblem_Btn")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(230, 470, 211, 80))
        self.groupBox.setObjectName("groupBox")
        self.words_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.words_radioButton.setGeometry(QtCore.QRect(10, 50, 95, 20))
        self.words_radioButton.setChecked(True)
        self.words_radioButton.setObjectName("words_radioButton")
        self.letters_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.letters_radioButton.setEnabled(False)
        self.letters_radioButton.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.letters_radioButton.setAcceptDrops(False)
        self.letters_radioButton.setChecked(False)
        self.letters_radioButton.setObjectName("letters_radioButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 470, 201, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.csp_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.csp_radioButton.setGeometry(QtCore.QRect(10, 50, 95, 20))
        self.csp_radioButton.setChecked(False)
        self.csp_radioButton.setObjectName("csp_radioButton")
        self.astar_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.astar_radioButton.setEnabled(True)
        self.astar_radioButton.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.astar_radioButton.setCheckable(True)
        self.astar_radioButton.setChecked(True)
        self.astar_radioButton.setObjectName("astar_radioButton")
        self.logWidget = QtWidgets.QListWidget(Dialog)
        self.logWidget.setGeometry(QtCore.QRect(460, 40, 351, 681))
        self.logWidget.setObjectName("logWidget")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 110, 421, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridDropDown = QtWidgets.QComboBox(Dialog)
        self.gridDropDown.setGeometry(QtCore.QRect(20, 10, 421, 41))
        self.gridDropDown.setObjectName("gridDropDown")
        self.loadDictionaryBtn = QtWidgets.QPushButton(Dialog)
        self.loadDictionaryBtn.setGeometry(QtCore.QRect(300, 60, 141, 41))
        self.loadDictionaryBtn.setObjectName("loadDictionaryBtn")
        self.solverList = QtWidgets.QComboBox(Dialog)
        self.solverList.setGeometry(QtCore.QRect(180, 560, 251, 41))
        self.solverList.setObjectName("solverList")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 570, 151, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(460, 10, 121, 21))
        self.label_2.setObjectName("label_2")
        self.renderSolutions = QtWidgets.QLabel(Dialog)
        self.renderSolutions.setGeometry(QtCore.QRect(30, 610, 251, 41))
        self.renderSolutions.setObjectName("renderSolutions")
        self.nbsolutionsList = QtWidgets.QComboBox(Dialog)
        self.nbsolutionsList.setGeometry(QtCore.QRect(280, 610, 151, 41))
        self.nbsolutionsList.setObjectName("nbsolutionsList")
        self.dicNameText = QtWidgets.QLineEdit(Dialog)
        self.dicNameText.setGeometry(QtCore.QRect(152, 61, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.dicNameText.setFont(font)
        self.dicNameText.setObjectName("dicNameText")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 121, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.solveProblem_Btn.setText(_translate("Dialog", "Solve It ! "))
        self.groupBox.setTitle(_translate("Dialog", "By"))
        self.words_radioButton.setText(_translate("Dialog", "Words"))
        self.letters_radioButton.setText(_translate("Dialog", "Letters"))
        self.groupBox_2.setTitle(_translate("Dialog", "Algorithm"))
        self.csp_radioButton.setText(_translate("Dialog", "CSP"))
        self.astar_radioButton.setText(_translate("Dialog", "A*"))
        self.loadDictionaryBtn.setText(_translate("Dialog", "Load Dictionary"))
        self.label.setText(_translate("Dialog", "Choose Solver (A* Only )"))
        self.label_2.setText(_translate("Dialog", "Log History"))
        self.renderSolutions.setText(_translate("Dialog", "Number of Solutions to Render (CSP only)"))
        self.dicNameText.setText(_translate("Dialog", "words.txt"))
        self.label_3.setText(_translate("Dialog", "Dictionary Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

